# Generated by Django 5.0.6 on 2025-10-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="latitude",
            field=models.FloatField(default=33.749),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="longitude",
            field=models.FloatField(default=-84.388),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="region",
            field=models.CharField(default="Atlanta", max_length=100),
        ),
    ]
