# Generated by Django 5.0.6 on 2025-10-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="city",
            field=models.CharField(default="Atlanta", max_length=100),
        ),
        migrations.AddField(
            model_name="review",
            name="region",
            field=models.CharField(default="Georgia", max_length=100),
        ),
    ]
