# Generated by Django 5.0.6 on 2025-10-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_review_city_review_region"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="city",
        ),
        migrations.RemoveField(
            model_name="review",
            name="region",
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(default="Atlanta", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="region",
            field=models.CharField(default="Georgia", max_length=100),
        ),
    ]
