# Generated by Django 5.0.6 on 2025-10-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_orderitem_latitude_orderitem_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
